### ISSUE TITLE
Expand and build on the theoretical dimensions we outlined

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#1]
Do states see NGOs as politically neutral? In theory they should, since that's the idea of the third sector, but we show that they don't—NGOs are political actors here

**Comment by yemeng-emma** [comment]
Add stuff from Anthony DeMattee and his work on closing space, with various forms of legal restrictions

**Comment by yemeng-emma** [comment]
Also to add de facto vs. de jure literature

**Comment by yemeng-emma** [comment]
Policy tools concepts too.
