### ISSUE TITLE
Clarify difference between domestic and overseas NGOs and the particular political threat raised by INGOs

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#12]
From Lauren MacLean:

> It’s important to be clear that China’s law regulates “overseas NGOs”, which is a different dynamic than the restrictions on local NGOs. The political threat is perceived in different terms as the threat of foreign influence and intervention in political sovereignty rather than an internal political threat from what are frequently perceived as opposition-aligned NGOs. What are the implications of this difference?

**Comment by yemeng-emma** [comment]
I think we can keep in mind that the discussion should be centered around the crack-down of international/foreign ngos but don't think it is necessary or helpful to separately explain these are two different kinds of ngos. Domestic CSOs are highly reliant on international funders and are also greatly impacted by the law.
