### ISSUE TITLE
Talk more about the issue areas of non-allowed INGOs, like the contentious human rights ones that are missing

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#13]
From Lauren MacLean:

> It’s not clear whether this ONGO law applies to NGOs doing more explicitly political work on human rights, environmental justice, labor rights, etc.?

**Comment by yemeng-emma** [comment]
The "de facto" reason is the Official don't like these NGOs. The "de jure" reason is the law does list all the more friendly issue areas in Article 3 but not the contentious ones. There are also articles that require all INGOs not to jeopardize "national security".

**Comment by yemeng-emma** [comment]
Article 3 Overseas NGOs may, in accordance with the provisions of this Law, engage in undertakings of benefit to the public in the areas of the economy, education, science, culture, health, sports and environmental protection, as well as in the areas of poverty and disaster relief.

**Comment by yemeng-emma** [comment]
Article 5 Activities of overseas NGOs in the mainland of China shall abide by Chinese laws and shall not threaten China’s national reunification and security or ethnic unity, nor harm China’s national and social interests or the legitimate rights and interests of citizens, legal persons and other organizations.

Overseas NGOs shall not engage in or finance profit-making or political activities in the mainland of China, and they shall not illegally engage in or finance religious activities.

**Comment by yemeng-emma** [comment]
To incorporate this in the conclusion section
