### ISSUE TITLE
Clarify/justify # of provinces earlier and describe tri-modal outcome earlier too

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#14]
From Lauren MacLean:

> Not sure about using the number of provinces that INGOs are allowed to operate in as a proxy for their operational space. Wouldn’t some INGOs choose to operate in a more localized space? You seem to acknowledge this later on p. 13. I’m not sure that the provinces permitted is a good measure of the possibility of constricting space for civil society. The number of provinces is really skewed – with high number of O values and high number of ALL. What does this mean for the analysis and your interpretation of the implementation of this law? Seems like all or nothing. You talk about this in terms of your modeling strategy but I would like to get a sense of your interpretation of this descriptive data first. 

We can justify this by talking about local connections earlier too. For INGOs with a local focus, there's no need to pursue nationwide reach, so geographic reach doesn't matter - that's why we control for local connections - it matters a lot. For INGOs without a local focus, though, they arguably care about having a wider reach to get more access to the country

**Comment by yemeng-emma** [comment]
We may want to go a little more conservative in interpreting the counts of provinces. Maybe we don't ambitiously claim the count is a proxy for the big construct of flexibility, but geographical room, operating space or some other more specific dimensions / relevant concepts. 

And agree that we should highlight the local_connect variable.
