### ISSUE TITLE
Better conceptualization of contentiousness and maybe predictions/explanations of contentious vs. noncontentious issues in China (like education feels noncontentious but it's not) and explain counter-intuitive results

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#15]
From Lauren MacLean:

> The hypothesis that less contentious INGOs would be less restricted seems straightforward. But, I am still not clear about how you conceptualize and measure “contentiousness”. I would not have predicted education to be more contentious than environment for example. Can you make it more clear how you are arriving at these estimations? Also, is this going to be empirically bounded by various states and regimes? So China-specific in this case?

**Comment by andrewheiss** [comment]
Use that German foundation as an example?

**Comment by yemeng-emma** [comment]
This is the same issue as our next task of reframing the whole paper: making the research question clearer, what literature we engage with and what the contribution of our paper is.

**Comment by yemeng-emma** [comment]
Another issue raised the same question on the counter-intuitive results. 

From Lauren MacLean:

The finding that is the reverse of your expectation seems intuitive to me. It may be that there is an increase in bureaucratic competence. Or an increase in learning that is shared among INGOs over time. Are there any umbrella organizations or TANs where INGOs working in China might share information about the registration process or share personal contacts for facilitating the process?

**Comment by yemeng-emma** [comment]
The environment group is higher can be explained like this. Those did get registered are the relatively mild and technical ones. The Nature Conservancy, for example. I interviewed them in 2017. They provided a lot of consultancy and technical support for the government, both national and local level. Comparatively, Greenpeace could not register and operates with filing TAs.

**Comment by yemeng-emma** [comment]
To cite this paper for the conceptualization of contentiousness. 
"[When Transnational Advocacy Meets China: INGO’s Strategic Norm Adaptation](https://www.jstor.org/stable/48635896)"
