### ISSUE TITLE
Add more explanation/speculation for reversed finding in expectation 3

### ISSUE THREAD

**Issue by andrewheiss** [andrewheiss/compassionate-clam#17]
From Lauren MacLean:

> The finding that is the reverse of your expectation seems intuitive to me. It may be that there is an increase in bureaucratic competence. Or an increase in learning that is shared among INGOs over time. Are there any umbrella organizations or TANs where INGOs working in China might share information about the registration process or share personal contacts for facilitating the process?

**Comment by yemeng-emma** [comment]
I think #15 raised the same question so I am closing this on and pasting this comment to that task.
